on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Should fail exit code 42
    steps:
      - uses: actions/checkout@v2
        with:
          # Contains [ci skip] in message body
          ref: 'c8c3a6c540e19b25e1cc6a560db9fca36cff495d'
          fetch-depth: '0'
      - uses: mstachniuk/ci-skip@master
        with:
          fail-fast: true
      - name: Check env
        run: |
          echo "The previous step should exiting with 42 code"