on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Should success
    steps:
      - uses: actions/checkout@v2
        with:
          # Contains [ci skip] in message body
          ref: 'c8c3a6c540e19b25e1cc6a560db9fca36cff495d'
          fetch-depth: '0'
      - uses: mstachniuk/ci-skip@master
      - name: Check env
        run: |
          echo "CI_SKIP is $CI_SKIP"
          echo "CI_SKIPNOT is $CI_SKIP_NOT"
          if [[ "$CI_SKIP" != true ]]; then
            echo "The CI_SKIP env should be set to true, but it is: $CI_SKIP"
            exit 1
          fi
          if [[ "$CI_SKIP_NOT" != false ]]; then
            echo "The CI_SKIP_NOT env should be set to false, but it is: $CI_SKIP_NOT"
            exit 2
          fi
